services:
  - type: web
    name: zoolocasino
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn zoolocasino_cloud:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
